version: '3.8'

services:
  app:
    image: ibootio/iprint:latest
    container_name: iboot-iprint
    ports:
      - "58080:58080"
    volumes:
      - ./config/application-prod.yaml:/app/config/application-prod.yaml
      - ./logs:/app/logs
    restart: unless-stopped
