version: '3.8'

services:
  app:
    image: ibootio/iprint:latest
    container_name: iboot-iprint
    network_mode: host
    ports:
      - "58080:58080"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
