/*
 Navicat Premium Dump SQL

 Source Server         : postgres17_5432_(pwd123456）
 Source Server Type    : PostgreSQL
 Source Server Version : 170005 (170005)
 Source Host           : localhost:5432
 Source Catalog        : iboot_iprint
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 170005 (170005)
 File Encoding         : 65001

 Date: 17/02/2026 18:57:30
*/


-- ----------------------------
-- Sequence structure for sys_api_key_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."sys_api_key_id_seq";
CREATE SEQUENCE "public"."sys_api_key_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sys_print_template_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."sys_print_template_id_seq";
CREATE SEQUENCE "public"."sys_print_template_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for sys_user_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."sys_user_id_seq";
CREATE SEQUENCE "public"."sys_user_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for sys_api_key
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_api_key";
CREATE TABLE "public"."sys_api_key" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "api_key" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "created_at" timestamp(6) NOT NULL,
  "description" varchar(500) COLLATE "pg_catalog"."default",
  "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "status" int4 NOT NULL,
  "updated_at" timestamp(6) NOT NULL
)
;

-- ----------------------------
-- Records of sys_api_key
-- ----------------------------
INSERT INTO "public"."sys_api_key" VALUES (1, '678b3baa23f64b758d8dbdec3fa445bd290a3d28c4934cf0', '2026-02-15 22:45:41.894296', '', 'test', 1, '2026-02-16 12:04:58.762272');

-- ----------------------------
-- Table structure for sys_print_template
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_print_template";
CREATE TABLE "public"."sys_print_template" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "code" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "created_at" timestamp(6) NOT NULL,
  "name" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "print_data" text COLLATE "pg_catalog"."default",
  "template_data" text COLLATE "pg_catalog"."default",
  "updated_at" timestamp(6) NOT NULL
)
;

-- ----------------------------
-- Records of sys_print_template
-- ----------------------------
INSERT INTO "public"."sys_print_template" VALUES (1, 'test', '2026-02-16 00:39:58.957075', '测试模版', '[
        {
            "a": "6669999",
            "b": "99999999",
            "c": "dsds",
            "d": "dsdsdsdsd",
            "e": "dsdsds",
            "v": "dsds",
            "users": [
                {
                    "name": "jack",
                    "account": "男"
                },
                {
                    "name": "tom",
                    "account": "https://github.com/anganing"
                }
            ],
            "url": "https://github.com/anganing"
        },
        {
            "a": 6669999,
            "b": 99999999,
            "v": 43,
            "users": [
                {
                    "name": "杰克",
                    "sex": "男"
                },
                {
                    "name": "玛丽",
                    "sex": "女"
                }
            ],
            "url": "https://github.com/anganing"
        }
    ]', '{"panels":[{"index":0,"name":1,"height":297,"width":210,"paperHeader":49.5,"paperFooter":780.0000000000001,"printElements":[{"options":{"left":45,"top":15,"height":9.75,"width":120,"title":"文本","right":165,"bottom":24.75,"vCenter":105,"hCenter":19.875,"field":"a","testData":"666","coordinateSync":false,"widthHeightSync":false,"qrCodeLevel":0},"printElementType":{"title":"文本","type":"text"}},{"options":{"left":22.5,"top":63,"height":74,"width":550,"field":"table","groupFooterFormatter":"function groupFooterFormatter(group, option) {\n          return \"这里自定义统计脚信息\";\n        }","groupFieldsFormatter":"function(type,options,data){ return [\"name\"] }","qid":"table","columns":[[{"width":69.99999999999999,"title":"行号","field":"id","checked":true,"columnId":"id","fixed":false,"rowspan":2,"colspan":1},{"width":100,"title":"人员信息","checked":true,"fixed":false,"rowspan":1,"colspan":2},{"width":100,"title":"销售统计","checked":true,"fixed":false,"rowspan":1,"colspan":2}],[{"width":120,"title":"姓名","field":"name","checked":true,"columnId":"name","fixed":false,"rowspan":1,"colspan":1,"align":"left"},{"width":120,"title":"性别","field":"gender","checked":true,"columnId":"gender","fixed":false,"rowspan":1,"colspan":1},{"width":120,"title":"销售数量","field":"count","checked":true,"columnId":"count","fixed":false,"rowspan":1,"colspan":1},{"width":120,"title":"销售金额","field":"amount","checked":true,"columnId":"amount","fixed":false,"rowspan":1,"colspan":1}]]},"printElementType":{"title":"表格","type":"table","editable":true,"columnDisplayEditable":true,"columnDisplayIndexEditable":true,"columnTitleEditable":true,"columnResizable":true,"columnAlignEditable":true,"isEnableEditField":true,"isEnableContextMenu":true,"isEnableInsertRow":true,"isEnableDeleteRow":true,"isEnableInsertColumn":true,"isEnableDeleteColumn":true,"isEnableMergeCell":true}},{"options":{"left":30,"top":183,"height":50,"width":50,"textType":"qrcode","title":"二维码","field":"b","testData":"b","coordinateSync":false,"widthHeightSync":false,"qrCodeLevel":0},"printElementType":{"title":"二维码","type":"text"}},{"options":{"left":171,"top":195,"height":35,"width":140,"textType":"barcode","title":"123456789","field":"v","testData":"v","coordinateSync":false,"widthHeightSync":false,"qrCodeLevel":0},"printElementType":{"title":"123456789","type":"text"}},{"options":{"left":27,"top":262.5,"height":36,"width":550,"field":"users","coordinateSync":false,"widthHeightSync":false,"columns":[[{"width":275,"title":"姓名","field":"name","checked":true,"columnId":"name","fixed":false,"rowspan":1,"colspan":1},{"width":275,"title":"账号","field":"account","checked":true,"columnId":"account","fixed":false,"rowspan":1,"colspan":1,"tableTextType":"qrcode","tableQRCodeLevel":0,"tableSummaryTitle":true,"tableSummary":""},{"width":100,"title":"","field":"","checked":false,"columnId":"","fixed":false,"rowspan":1,"colspan":1},{"width":100,"title":"","field":"","checked":false,"columnId":"","fixed":false,"rowspan":1,"colspan":1}]]},"printElementType":{"title":"空白表格","type":"table","editable":true,"columnDisplayEditable":true,"columnDisplayIndexEditable":true,"columnTitleEditable":true,"columnResizable":true,"columnAlignEditable":true,"isEnableEditField":true,"isEnableContextMenu":true,"isEnableInsertRow":true,"isEnableDeleteRow":true,"isEnableInsertColumn":true,"isEnableDeleteColumn":true,"isEnableMergeCell":true}},{"options":{"left":135,"top":352.5,"height":9.75,"width":120,"title":"自定义文本","right":255.0000228881836,"bottom":361.5000228881836,"vCenter":195.0000228881836,"hCenter":356.6250228881836,"field":"e","testData":"e","coordinateSync":false,"widthHeightSync":false,"qrCodeLevel":0},"printElementType":{"title":"自定义文本","type":"text"}},{"options":{"left":319.5,"top":352.5,"height":42,"width":183,"title":"长文","right":502.5,"bottom":393.7500343322754,"vCenter":411,"hCenter":372.7500343322754,"field":"d","testData":"d","coordinateSync":false,"widthHeightSync":false},"printElementType":{"title":"长文","type":"longText"}},{"options":{"left":58.5,"top":366,"height":90,"width":90,"formatter":"function formatter(data, options) {\n          return ''<div style=\"height:50pt;width:50pt;background:red;border-radius: 50%;\"></div>'';\n        }"},"printElementType":{"title":"html","type":"html"}},{"options":{"left":207,"top":418.5,"height":90,"width":9},"printElementType":{"title":"竖线","type":"vline"}},{"options":{"left":478.5,"top":435,"height":90,"width":90},"printElementType":{"title":"椭圆","type":"oval"}},{"options":{"left":54,"top":447,"height":9,"width":90,"borderWidth":0.75},"printElementType":{"title":"横线","type":"hline"}},{"options":{"left":294,"top":454.5,"height":90,"width":90},"printElementType":{"title":"矩形","type":"rect"}},{"options":{"left":127.5,"top":574.5,"height":35,"width":140,"textType":"barcode","title":"123456789"},"printElementType":{"title":"123456789","type":"text"}},{"options":{"left":279,"top":627,"height":50,"width":50,"textType":"qrcode","title":"二维码"},"printElementType":{"title":"二维码","type":"text"}}],"paperNumberLeft":565.5,"paperNumberTop":573,"paperNumberContinue":true,"watermarkOptions":{"content":"vue-plugin-hiprint","rotate":25,"timestamp":true,"format":"YYYY-MM-DD HH:mm"},"panelLayoutOptions":{}}]}', '2026-02-16 16:35:15.572762');
INSERT INTO "public"."sys_print_template" VALUES (3, 'test2', '2026-02-16 21:21:25.626247', 't', '[{
  "a": 123,
  "b": 4567
}]', '{"panels":[{"index":0,"name":1,"paperType":"A4","height":297,"width":210,"paperHeader":0,"paperFooter":841.8897637795277,"printElements":[{"options":{"left":81,"top":81,"height":50,"width":50,"textType":"qrcode","title":"二维码","field":"a","testData":"1234","coordinateSync":false,"widthHeightSync":false,"qrCodeLevel":0},"printElementType":{"title":"二维码","type":"text"}},{"options":{"left":181.5,"top":93,"height":35,"width":140,"textType":"barcode","title":"123456789","field":"b","testData":"12345667","coordinateSync":false,"widthHeightSync":false,"qrCodeLevel":0},"printElementType":{"title":"123456789","type":"text"}},{"options":{"left":18,"top":193.5,"height":36,"width":550,"right":568,"bottom":229.5000114440918,"vCenter":293,"hCenter":211.5000114440918,"columns":[[{"width":275,"title":"","field":"","checked":true,"columnId":"","fixed":false,"rowspan":1,"colspan":1},{"width":275,"title":"","field":"","checked":true,"columnId":"","fixed":false,"rowspan":1,"colspan":1}]]},"printElementType":{"title":"空白表格","type":"table","editable":true,"columnDisplayEditable":true,"columnDisplayIndexEditable":true,"columnTitleEditable":true,"columnResizable":true,"columnAlignEditable":true,"isEnableEditField":true,"isEnableContextMenu":true,"isEnableInsertRow":true,"isEnableDeleteRow":true,"isEnableInsertColumn":true,"isEnableDeleteColumn":true,"isEnableMergeCell":true}},{"options":{"left":25.5,"top":267,"height":74,"width":550,"field":"table","groupFooterFormatter":"function(Be,De){return\"这里自定义统计脚信息\"}","groupFieldsFormatter":"function(type,options,data){ return [\"name\"] }","qid":"table","right":574.75,"bottom":341.0000114440918,"vCenter":299.75,"hCenter":304.0000114440918,"columns":[[{"width":69.99999999999999,"title":"行号","field":"id","checked":true,"columnId":"id","fixed":false,"rowspan":2,"colspan":1},{"width":100,"title":"人员信息","checked":true,"fixed":false,"rowspan":1,"colspan":2},{"width":100,"title":"销售统计","checked":true,"fixed":false,"rowspan":1,"colspan":2}],[{"width":120,"title":"姓名","field":"name","checked":true,"columnId":"name","fixed":false,"rowspan":1,"colspan":1,"align":"left"},{"width":120,"title":"性别","field":"gender","checked":true,"columnId":"gender","fixed":false,"rowspan":1,"colspan":1},{"width":120,"title":"销售数量","field":"count","checked":true,"columnId":"count","fixed":false,"rowspan":1,"colspan":1},{"width":120,"title":"销售金额","field":"amount","checked":true,"columnId":"amount","fixed":false,"rowspan":1,"colspan":1}]]},"printElementType":{"title":"表格","type":"table","editable":true,"columnDisplayEditable":true,"columnDisplayIndexEditable":true,"columnTitleEditable":true,"columnResizable":true,"columnAlignEditable":true,"isEnableEditField":true,"isEnableContextMenu":true,"isEnableInsertRow":true,"isEnableDeleteRow":true,"isEnableInsertColumn":true,"isEnableDeleteColumn":true,"isEnableMergeCell":true}}],"paperNumberContinue":true,"watermarkOptions":{},"panelLayoutOptions":{}}]}', '2026-02-16 21:27:43.549858');

-- ----------------------------
-- Table structure for sys_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."sys_user";
CREATE TABLE "public"."sys_user" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "created_at" timestamp(6) NOT NULL,
  "password" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "updated_at" timestamp(6) NOT NULL,
  "username" varchar(50) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of sys_user
-- ----------------------------
INSERT INTO "public"."sys_user" VALUES (1, '2026-02-15 22:32:26.710813', '$2a$10$c6GfRrPqdxrRklIyw6GwduSjZ3YD7fNXQMpSI1VXxHDCFasNsBjt6', '2026-02-15 22:44:14.008977', 'admin');

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."sys_api_key_id_seq"
OWNED BY "public"."sys_api_key"."id";
SELECT setval('"public"."sys_api_key_id_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."sys_print_template_id_seq"
OWNED BY "public"."sys_print_template"."id";
SELECT setval('"public"."sys_print_template_id_seq"', 3, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."sys_user_id_seq"
OWNED BY "public"."sys_user"."id";
SELECT setval('"public"."sys_user_id_seq"', 1, true);

-- ----------------------------
-- Auto increment value for sys_api_key
-- ----------------------------
SELECT setval('"public"."sys_api_key_id_seq"', 1, true);

-- ----------------------------
-- Uniques structure for table sys_api_key
-- ----------------------------
ALTER TABLE "public"."sys_api_key" ADD CONSTRAINT "uk5jqsvjvy48394hg6fbd4yrotj" UNIQUE ("api_key");

-- ----------------------------
-- Primary Key structure for table sys_api_key
-- ----------------------------
ALTER TABLE "public"."sys_api_key" ADD CONSTRAINT "sys_api_key_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for sys_print_template
-- ----------------------------
SELECT setval('"public"."sys_print_template_id_seq"', 3, true);

-- ----------------------------
-- Uniques structure for table sys_print_template
-- ----------------------------
ALTER TABLE "public"."sys_print_template" ADD CONSTRAINT "uka2mxiueu5h3u0eg7l1nrbfgds" UNIQUE ("code");

-- ----------------------------
-- Primary Key structure for table sys_print_template
-- ----------------------------
ALTER TABLE "public"."sys_print_template" ADD CONSTRAINT "sys_print_template_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for sys_user
-- ----------------------------
SELECT setval('"public"."sys_user_id_seq"', 1, true);

-- ----------------------------
-- Uniques structure for table sys_user
-- ----------------------------
ALTER TABLE "public"."sys_user" ADD CONSTRAINT "uk51bvuyvihefoh4kp5syh2jpi4" UNIQUE ("username");

-- ----------------------------
-- Primary Key structure for table sys_user
-- ----------------------------
ALTER TABLE "public"."sys_user" ADD CONSTRAINT "sys_user_pkey" PRIMARY KEY ("id");
